FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y  \
    git wget sudo build-essential \
    python3 python3-setuptools python3-pip python3-dev python3-tk \
    ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    zsh tmux

RUN ln -svf /usr/bin/python3 /usr/bin/python
RUN python -m pip install --upgrade --force pip

# miniconda
# ENV PATH="/root/miniconda3/bin:${PATH}"
# ARG PATH="/root/miniconda3/bin:${PATH}"

# RUN wget \
#     https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
#     && mkdir /root/.conda \
#     && bash Miniconda3-latest-Linux-x86_64.sh -b \
#     && rm -f Miniconda3-latest-Linux-x86_64.sh 

# RUN conda --version

ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH
#

COPY environment.yml environment.yml

RUN conda env create -f environment.yml


RUN ln -s ${CONDA_DIR}/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
  && echo ". ${CONDA_DIR}/etc/profile.d/conda.sh" >> ~/.bashrc \
  && echo "conda activate minigptv" >> ~/.bashrc \
  && find ${CONDA_DIR}/ -follow -type f -name '*.a' -delete \
  && find ${CONDA_DIR}/ -follow -type f -name '*.js.map' -delete \
  && ${CONDA_DIR}/bin/conda clean -afy

RUN conda install -n minigptv ipykernel --update-deps --force-reinstall -y
RUN conda install -n minigptv -c conda-forge --update-deps typing-extensions

RUN echo "conda activate custom_env" >> ~/.bashrc
RUN echo "source activate minigptv" > ~/.bashrc

#### ADD USER WITH DEFAULT PW
ARG USER=docker_current
ARG UID=1000
ARG GID=1000
ARG PW=user

RUN useradd -m ${USER} --uid=${UID} && echo "${USER}:${PW}" | chpasswd && adduser ${USER} sudo
WORKDIR /home/${USER}
RUN chown -R ${UID}:${GID} /home/${USER}
USER ${UID}:${GID}